---
geometry:
  N_pixels: 256
  R_obj: 125
  D_sd: 1000
  D_so: 500

projection:
  N_det: 512
  N_views: 1000
  view_range: np.pi
  type: parallel

filter:
  type: "shepp-logan"
  cutoff: 0.01

interpolation:
  type: "linear"
  factor: 1
